💻 商品一覧、詳細機能実装
neco3s/rails_ec pull request #6
Opened 2023-06-10 02:49 UTC by neco3s

## 課題のリンク

* https://github.com/happiness-chain/practice/blob/main/11_Ruby_on_Rails/001.2_rails%E3%81%A7EC%E3%82%B5%E3%82%A4%E3%83%88%E3%82%92%E4%BD%9C%E3%82%8B.md#-%E5%95%86%E5%93%81%E4%B8%80%E8%A6%A7%E8%A9%B3%E7%B4%B0%E6%A9%9F%E8%83%BD%E5%AE%9F%E8%A3%85

## やったこと

* 初期スキーマの作成(仮)
* annotateの追加
* productモデルの作成
* active storege初期設定
* seedデータ作成
* product routesの追記
* products controllerの作成
* views/shared/_navigation.html.erb 　views/shared/_footer.html.erb パーシャル作成 
* products#indexに対応するviewの作成
* products#showに対応するvidwの作成

## 動作確認方法

* `git clone`
* `docker compose build`
* `docker compose run --rm web bin/setup`
* `docker compose run --rm web yarn install`
* `docker compose up`
*  http://localhost:3000 にbrowserからアクセス

## その他

* レビュワーへの参考情報（実装上の懸念点や注意点、困りごとなど）

2023-06-11 05:41 UTC, ihatov08 commented
> herokuでs3を使用していないので画像が表示されません!!🙇

herokuで画像が表示されるようにs3の使用をお願いします 🙇

2023-06-11 05:41 UTC, ihatov08 commented
> db設計をやってみたくて今回の課題の分ではないテーブルを作成してしまいました🙇

必要なテーブルのみ追加お願いします 🙇

2023-06-11 05:42 UTC, neco3s commented
> > herokuでs3を使用していないので画像が表示されません!!🙇
> 
> 
> 
> herokuで画像が表示されるようにs3の使用をお願いします 🙇 

承知いたしました！

2023-06-11 05:43 UTC, neco3s commented
> > db設計をやってみたくて今回の課題の分ではないテーブルを作成してしまいました🙇
> 
> 
> 
> 必要なテーブルのみ追加お願いします 🙇 

承知いたしました！

2023-06-12 02:32 UTC, ihatov08 commented
@neco3s 
public templateのせいなのかよくわからないのですが、Github Actionsが動作していないので、
動作するように修正お願いします！

2023-06-12 04:20 UTC, neco3s commented
> @neco3s public templateのせいなのかよくわからないのですが、Github Actionsが動作していないので、 動作するように修正お願いします！

@ihatov08 

承知いたしました!! いつから動かなくなったのか確認しながら修正してみたいと思います!:bow:

2023-06-12 05:05 UTC, neco3s commented
@ihatov08 

修正完了いたしました!!:bow:

2023-06-12 06:10 UTC, ihatov08 requested changes
> ※以下で使用するテンプレートは英語表記ですが、日本語表記や並びに変更してください。

こちら対応お願いします！

2023-06-12 06:13 UTC, neco3s commented
> > ※以下で使用するテンプレートは英語表記ですが、日本語表記や並びに変更してください。
> 
> こちら対応お願いします！

完全に読み飛ばしていました💦 修正いたします!!

2023-06-12 06:55 UTC, neco3s commented
> > ※以下で使用するテンプレートは英語表記ですが、日本語表記や並びに変更してください。
> 
> こちら対応お願いします！

修正完了いたしました!! :bow:

2023-06-12 07:11 UTC, ihatov08 commented
![Myapp (15)](https://github.com/neco3s/rails_ec/assets/14024165/f0a50ae2-e6cb-4374-94bd-5565c95bbb69)

円表記がおかしいでーす！
普通は前にくるはずです。

2023-06-12 07:16 UTC, neco3s commented
> ![Myapp (15)](https://github.com/neco3s/rails_ec/assets/14024165/f0a50ae2-e6cb-4374-94bd-5565c95bbb69)
> 
> 
> 
> 円表記がおかしいでーす！
> 
> 普通は前にくるはずです。

今までずっと後ろに来るものだと思ってました!!!修正します！

![image](https://github.com/neco3s/rails_ec/assets/88125637/41f6b0be-82ae-49ed-ae23-08251a24cd39)

![image](https://github.com/neco3s/rails_ec/assets/88125637/c1808b71-0660-4f84-96b7-0f6e9a031b85)

2023-06-12 07:21 UTC, neco3s commented
> ![Myapp (15)](https://user-images.githubusercontent.com/14024165/245059593-f0a50ae2-e6cb-4374-94bd-5565c95bbb69.jpg)
> 
> 円表記がおかしいでーす！ 普通は前にくるはずです。

修正いたしました!! 先頭につくんですね!

<img width="1247" alt="スクリーンショット 2023-06-12 16 20 33" src="https://github.com/neco3s/rails_ec/assets/88125637/d3268f85-62cc-4fac-9883-98de1e8640cf">


https://damp-anchorage-33119.herokuapp.com/

2023-06-12 07:24 UTC, ihatov08 approved these changes
確認しました、LGTMです！

2023-06-12 07:25 UTC, merged