💻 商品管理機能
neco3s/rails_ec pull request #8
Opened 2023-06-21 03:38 UTC by neco3s

## 課題のリンク

* https://github.com/happiness-chain/practice/blob/main/11_Ruby_on_Rails/001.2_rails%E3%81%A7EC%E3%82%B5%E3%82%A4%E3%83%88%E3%82%92%E4%BD%9C%E3%82%8B.md#-%E5%95%86%E5%93%81%E7%AE%A1%E7%90%86%E6%A9%9F%E8%83%BD

## やったこと

* Basic Authの実装
* 商品一覧画面
* 登録機能
* 編集機能
* 削除機能
* heroku deploy & 環境変数設定

## 動作確認方法

* `git clone`
* `docker compose build`
* `docker compose run --rm web bin/setup`
* `docker compose run --rm web yarn install`
* `docker compose up`
*  http://localhost:3000 にbrowserからアクセス

または以下のサイトにアクセス
https://damp-anchorage-33119.herokuapp.com/admin/products

name=heroku_neco3s
password=heroku_password

## その他

* レビュワーへの参考情報（実装上の懸念点や注意点、困りごとなど）

2023-06-21 03:39 UTC, neco3s commented
rubocop, 修正中です....:bow:

2023-06-21 08:58 UTC, ihatov08 requested changes
> basic認証はユーザー名(admin),パスワード(pw)とすること


対応お願いします！

2023-06-21 09:20 UTC, neco3s commented
> > basic認証はユーザー名(admin),パスワード(pw)とすること
> 
> 対応お願いします！

@ihatov08 
すいません! 読み飛ばしていました!!:bow:

name=admin
password=pw

に修正致しました

2023-06-21 10:38 UTC, ihatov08 commented on app/controllers/admin/products_controller.rb
> +    def create
基本に忠実に実装しましょう。

以下を参考に修正お願いします。
https://qiita.com/jnchito/items/2b57316b39d92ca0e8dc

- エラーハンドリング
- 成功時、失敗時のflashメッセージ
- viewにvalidationエラー表示

2023-06-21 10:40 UTC, ihatov08 commented
何も入力しないで登録するとエラーが起きます。

![Action-Controller-Exception-caught (4)](https://github.com/neco3s/rails_ec/assets/14024165/b9b24d93-244a-4eee-aeb5-4d009911631d)

エラーハンドリングをちゃんと実装してください！

2023-06-21 10:50 UTC, neco3s commented on app/controllers/admin/products_controller.rb
> +    def create
> 基本に忠実に実装しましょう。
> 
> 以下を参考に修正お願いします。
> https://qiita.com/jnchito/items/2b57316b39d92ca0e8dc
> 
> エラーハンドリング
> 成功時、失敗時のflashメッセージ
> viewにvalidationエラー表示


レビュー&参考URL教えて頂きありがとうございます🙇

修正致します!!!!

2023-06-21 11:27 UTC, neco3s commented
> 何も入力しないで登録するとエラーが起きます。
> 
> ![Action-Controller-Exception-caught (4)](https://user-images.githubusercontent.com/14024165/247521153-b9b24d93-244a-4eee-aeb5-4d009911631d.jpg)
> 
> エラーハンドリングをちゃんと実装してください！

すいません!!

記事共有して頂きありがとうございます:bow:

修正中です!!
> 「モデルではなくサービスクラスを用意してそこにロジックを書くべきでは？」という意見が挙がりますが、個人的にはコントローラに限らず、設計全体をscaffoldの形から崩さない（scaffoldにないクラスはなるべく作らない）方がRails wayだと考えています。なので、僕は「どのモデルがこのロジックの責務を持つべきか」を考えた上でモデルにロジックを書くようにしています。

2023-06-23 14:48 UTC, neco3s commented
レビューいただいた箇所の修正完了いたしました!!!:bow:

2023-06-24 13:44 UTC, ihatov08 commented on app/models/product.rb
> +  # validates :description, length: { maximum: 300 } # 300文字以内の商品説明を想定
TODOしていたら課題の意味がないので、ja.ymlを正常に動作するようにしてください！

2023-06-24 13:44 UTC, ihatov08 commented on Procfile.dev
> +css: bin/rails tailwindcss:watch
tailwindは不要なはずです。

2023-06-24 13:46 UTC, ihatov08 requested changes
自動でセール品になり、割引になってしまうので修正お願いします！

2023-06-25 10:39 UTC, neco3s commented on Procfile.dev
> +css: bin/rails tailwindcss:watch
削除いたしました!:bow:

2023-06-25 10:39 UTC, neco3s commented on app/models/product.rb
> +  # validates :description, length: { maximum: 300 } # 300文字以内の商品説明を想定
削除いたしました!:bow:

2023-06-25 10:40 UTC, neco3s commented
> 自動でセール品になり、割引になってしまうので修正お願いします！

対応中です:bow:

2023-06-25 13:46 UTC, neco3s commented
@ihatov08 

> 自動でセール品になり、割引になってしまうので修正お願いします！

修正対応完了いたしました！！！！:bow:

2023-06-25 22:57 UTC, neco3s commented
編集機能が動いていないので修正対応中です!!:bow:
![スクリーンショット 2023-06-26 7 57 06](https://github.com/neco3s/rails_ec/assets/88125637/7d0a4cd3-ac0f-46ae-a42b-0e18cff8d32e)

2023-07-16 13:43 UTC, ihatov08 approved these changes
確認しました、LGTMです！

2023-07-16 22:02 UTC, merged

2023-07-16 23:07 UTC, neco3s commented
@ihatov08 
確認ありがとうございます!
マージいたしました！🙇‍♂️