💻 カート機能実装
neco3s/rails_ec pull request #9
Opened 2023-07-24 01:58 UTC by neco3s

## 課題のリンク

* https://github.com/happiness-chain/practice/blob/main/11_Ruby_on_Rails/001.2_rails%E3%81%A7EC%E3%82%B5%E3%82%A4%E3%83%88%E3%82%92%E4%BD%9C%E3%82%8B.md#-%E3%82%AB%E3%83%BC%E3%83%88%E6%A9%9F%E8%83%BD%E5%AE%9F%E8%A3%85

## やったこと

- カート機能の追加

* このプルリクで何をしたのか？

- カートに入った商品が他の人に奪われることがないようにした

## 動作確認方法

以下のサイトへアクセスしてください

https://lit-ridge-54246-f28a7a68ae97.herokuapp.com/

* 動作確認方法の手順を書いてください

- カートに入れるボタンを２〜３押す
- 右上のカートボタンを押す
- 商品を棚に戻すボタンを押す
- 会計ボタンを押す

## その他

* レビュワーへの参考情報（実装上の懸念点や注意点、困りごとなど）

2023-07-24 03:20 UTC, ihatov08 commented on app/controllers/products_controller.rb
> +# rubocop:enable Hc/RailsSpecificActionName, Layout/LineLength, Metrics/MethodLength, Metrics/AbcSize
ruHc/RailsSpecificActionNameは無効にしないでください。
Layout/LineLength, Metrics/MethodLength, Metrics/AbcSizeについても設定値が厳しければ向こうではなく、緩める方針でお願いします。

2023-07-24 04:02 UTC, neco3s commented on app/controllers/products_controller.rb
> +# rubocop:enable Hc/RailsSpecificActionName, Layout/LineLength, Metrics/MethodLength, Metrics/AbcSize
レビューありがとうございます:bow:

承知いたしました:bow:

cart_controllerを作成して以下のように修正したいと思います:bow:
```
  # cart_controller indexアクションに修正
  def cart

  # cart_controller showアクションに修正
  def checkout

  # cart_controller createアクションに修正
  def add_cart

  # cart_controller destroyアクションに修正
  def return_to_shelf
```

>Layout/LineLength, Metrics/MethodLength, Metrics/AbcSizeについても設定値が厳しければ向こうではなく、緩める方針でお願いします。

https://docs.rubocop.org/rubocop/configuration.html
こちらのサイトを参考にしながら緩めてみたいと思います:bow:

2023-07-24 04:12 UTC, ihatov08 requested changes
https://github.com/howardmann/Tutorials/blob/master/Rails_Shopping_Cart.md#carts-controller

こちらを参考に実装してみてください

2023-07-24 04:37 UTC, neco3s commented
@ihatov08 

> https://github.com/howardmann/Tutorials/blob/master/Rails_Shopping_Cart.md#carts-controller
こちらを参考に実装してみてください

共有して頂きありがとうございます!!:bow:

すごい参考になりました！

- コントローラーに直接書いてるロジックを重複してたらprivateの関数として定義してbefore_actionで実行する
- モデルにロジックをかけたら書く
- １つのコントローラに詰め込まずに複数のコントローラーに分割する

この辺りの修正を加えようと思います!:bow:

2025-12-19 13:02 UTC, necoffee-web commented
close します！！
お世話になりました！！

2025-12-19 13:02 UTC, closed without merging